# Generated by Django 5.1 on 2024-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_play_is_finished_play_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_players', models.IntegerField(choices=[(4, 'Quatre joueurs'), (8, 'Huit joueurs')], default=4)),
                ('results', models.JSONField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
